Update bitfields.md
antirez/redis-doc pull request #2560
Opened 2023-10-12 14:33 UTC by sav-norem

update bitfields data type page to include hugo short code - condense example and add relevant context

2023-10-12 14:34 UTC, sav-norem commented
@dwdougherty bitfields for your viewing pleasure

2023-10-16 20:58 UTC, dwdougherty requested changes
A few edits.

2023-10-16 20:58 UTC, dwdougherty commented on docs/data-types/bitfields.md
>  ## Examples
## Example

2023-10-16 20:58 UTC, dwdougherty commented on docs/data-types/bitfields.md
>  You can represent these counters with one bitfield per player.
```suggestion
Suppose you want to maintain two metrics for various bicycles: the current price and the number of owners over time. You can represent these counters with a 32-bit wide bitfield per for each bike.
```

2023-10-16 20:58 UTC, dwdougherty commented on docs/data-types/bitfields.md
> +* Bike 1 initially costs 1,000 (counter in offset 0) and has never had an owner. After being sold, it's now considered used and the price instantly drops to reflect its new condition, and it now has
```suggestion
* Bike 1 initially costs 1,000 (counter in offset 0) and has never had an owner. After being sold, it's now considered used and the price instantly drops to reflect its new condition, and it now has an owner (offset 1). After quite some time, the bike becomes a classic. The original owner sells it for a profit, so the price goes up and the number of owners does as well. Finally, you can look at the bike's current price and number of owners.
```

2023-10-24 15:33 UTC, sav-norem commented
@dwdougherty updated with feedback

2023-10-24 20:45 UTC, dwdougherty commented on docs/data-types/bitfields.md
> +{{< /clients-examples >}}
```suggestion
{{< /clients-example >}}
```

2024-01-16 15:40 UTC, merged