Update bitmaps.md
antirez/redis-doc pull request #2561
Opened 2023-10-12 17:27 UTC by sav-norem

update bitmaps data type page to include hugo short code - condensed example and added relevant context

2023-10-12 17:28 UTC, sav-norem commented
@dwdougherty the last data types docs page that needs hugo short codes at the moment

2023-10-16 21:01 UTC, dwdougherty requested changes
Just a coupla comments.

2023-10-16 21:01 UTC, dwdougherty commented on docs/data-types/bitmaps.md
> +* Rider 123 pings the server on January 1, 2024 within the 00:00 hour. We can then confirm that rider 123 pinged the server. We can then check to see if rider 456 has pinged the server for that same
```suggestion
* Rider 123 pings the server on January 1, 2024 within the 00:00 hour. You can then confirm that rider 123 pinged the server. You can also check to see if rider 456 has pinged the server for that same hour.
```

2023-10-24 20:46 UTC, dwdougherty commented on docs/data-types/bitmaps.md
> +{{< /clients-examples >}}
```suggestion
{{< /clients-example >}}
```

2023-10-24 20:47 UTC, dwdougherty requested changes
The closing tags weren't correct, causing build failure.

2023-10-24 20:47 UTC, dwdougherty commented on docs/data-types/bitmaps.md
> +{{< /clients-examples >}}
```suggestion
{{< /clients-example >}}
```

2023-10-25 15:47 UTC, dwdougherty approved these changes
Builds correctly. Approved.

2023-11-10 19:58 UTC, zuiderkwast commented on docs/data-types/bitmaps.md
> +You want to quickly determine whether a given rider has pinged a tracking server within the hour.
Sorry, but I think connected sensors are more common than connected cyclists. Or maybe it's a censor on each bicycle? :)

2023-11-10 20:09 UTC, sav-norem commented
I definitely meant it as a sensor on each bicycle! Can clarify that wording.

On Fri, Nov 10, 2023 at 2:58 PM Viktor Söderqvist ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In docs/data-types/bitmaps.md
> <https://github.com/redis/redis-doc/pull/2561#discussion_r1389857934>:
>
> > -Suppose you have 1000 sensors deployed in the field, labeled 0-999.
> -You want to quickly determine whether a given sensor has pinged the server within the hour.
> +Suppose you have 1000 cyclists racing through the country-side, labeled 0-999.
> +You want to quickly determine whether a given rider has pinged a tracking server within the hour.
>
> Sorry, but I think connected sensors are more common than connected
> cyclists. Or maybe it's a censor on each bicycle? :)
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/redis/redis-doc/pull/2561#pullrequestreview-1725537586>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AFKGFXXLCDCEHZWQO732BKLYD2BO5AVCNFSM6AAAAAA556NOHKVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTOMRVGUZTONJYGY>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-01-16 15:33 UTC, merged